/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 27 16:10:52 GMT 2019
 */

package com.adapterj.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import com.adapterj.widget.Anchor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Anchor_ESTest extends Anchor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Anchor anchor0 = new Anchor((String) null);
      String string0 = anchor0.getURL();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Anchor anchor0 = new Anchor("]");
      String string0 = anchor0.getURL();
      assertEquals("]", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Anchor anchor0 = new Anchor((String) null);
      String string0 = anchor0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Anchor anchor0 = new Anchor("]");
      anchor0.setURL("]");
      assertEquals("]", anchor0.getURL());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Anchor anchor0 = new Anchor("", "");
      String string0 = anchor0.toJSONString();
      assertEquals("{\"url\":\"\", \"text\":\"\"}", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Anchor anchor0 = new Anchor("");
      String string0 = anchor0.getURL();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Anchor anchor0 = new Anchor("]");
      anchor0.setText("]");
      String string0 = anchor0.getText();
      assertEquals("]", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Anchor anchor0 = new Anchor("", "");
      String string0 = anchor0.getText();
      assertEquals("", string0);
  }
}
