/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 27 14:35:36 GMT 2019
 */

package com.adapterj.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.adapterj.widget.SimpleSelectOptions;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleSelectOptions_ESTest extends SimpleSelectOptions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleSelectOptions simpleSelectOptions0 = null;
      try {
        simpleSelectOptions0 = new SimpleSelectOptions("", (Map<String, String>) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.adapterj.widget.SimpleSelectOptions", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleSelectOptions simpleSelectOptions0 = null;
      try {
        simpleSelectOptions0 = new SimpleSelectOptions("meta", (Map<Integer, String>) null, (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.adapterj.widget.SimpleSelectOptions", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleSelectOptions simpleSelectOptions0 = null;
      try {
        simpleSelectOptions0 = new SimpleSelectOptions("seect", (Map<String, String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.adapterj.widget.SimpleSelectOptions", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleSelectOptions simpleSelectOptions0 = null;
      try {
        simpleSelectOptions0 = new SimpleSelectOptions((String) null, (List<String>) null, 4595);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.adapterj.widget.SimpleSelectOptions", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleSelectOptions simpleSelectOptions0 = null;
      try {
        simpleSelectOptions0 = new SimpleSelectOptions((String) null, (List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.adapterj.widget.SimpleSelectOptions", e);
      }
  }
}
