/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 27 16:09:59 GMT 2019
 */

package com.adapterj.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import com.adapterj.widget.SimpleHTMLViewAccelerator1;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleHTMLViewAccelerator1_ESTest extends SimpleHTMLViewAccelerator1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleHTMLViewAccelerator1 simpleHTMLViewAccelerator1_0 = new SimpleHTMLViewAccelerator1();
      simpleHTMLViewAccelerator1_0.test((String) null);
      String string0 = simpleHTMLViewAccelerator1_0.test();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleHTMLViewAccelerator1 simpleHTMLViewAccelerator1_0 = new SimpleHTMLViewAccelerator1();
      simpleHTMLViewAccelerator1_0.test("");
      String string0 = simpleHTMLViewAccelerator1_0.test();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleHTMLViewAccelerator1 simpleHTMLViewAccelerator1_0 = new SimpleHTMLViewAccelerator1();
      String string0 = simpleHTMLViewAccelerator1_0.test();
      assertEquals("It's NOT working ...", string0);
  }
}
