/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 27 16:10:34 GMT 2019
 */

package com.adapterj.widget;

import org.junit.Test;
import static org.junit.Assert.*;
import com.adapterj.widget.Text;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Text_ESTest extends Text_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Text text0 = new Text("");
      String string0 = text0.getText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Text text0 = new Text(".^9)lx%])R7'f><'S6");
      String string0 = text0.getText();
      assertEquals(".^9)lx%])R7'f><'S6", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Text text0 = new Text(".^9)lx%])R7'f><'S6");
      text0.setText((String) null);
      String string0 = text0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Text text0 = new Text("I&D;");
      String string0 = text0.toJSONString();
      assertEquals("{\"text\":\"I&D;\"}", string0);
  }
}
