/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 27 16:05:43 GMT 2019
 */

package com.adapterj.html;

import org.junit.Test;
import static org.junit.Assert.*;
import com.adapterj.html.Attributes;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Attributes_ESTest extends Attributes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Attributes.toString((-4281));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = Attributes.toString(261);
      assertEquals("refresh", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = Attributes.toString(260);
      assertNotNull(string0);
      assertEquals("default-style", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = Attributes.toString(259);
      assertEquals("content-type", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = Attributes.toString(258);
      assertEquals("content-security-policy", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = Attributes.toString(262);
      assertNotNull(string0);
      assertEquals("set-cookie", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = Attributes.toString(257);
      assertNotNull(string0);
      assertEquals("content-language", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      assertEquals(262, Attributes.HTTP_EQUIV_SET_COOKIE);
  }
}
